# Generated by Django 5.1.1 on 2024-10-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_clientmodel_project_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='project_history',
            new_name='additional_info',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('freelancer', 'Freelancer')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='verification_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='freelancermodel',
            name='verification_status',
            field=models.BooleanField(default=True),
        ),
    ]
