# Generated by Django 5.1.1 on 2024-10-08 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0002_initial'),
        ('other', '0001_initial'),
        ('project', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.clientmodel'),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='freelancer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.freelancermodel'),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='project.projectmodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='other.conversationmodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='offer.offermodel'),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='rated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='rater_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
