# Generated by Django 5.1 on 2024-10-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
