# Generated by Django 5.1.1 on 2024-10-08 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0002_initial'),
        ('project', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='user.freelancermodel'),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='offer.offermodel'),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='project.projectmodel'),
        ),
        migrations.AddField(
            model_name='deliverablemodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='project.projectmodel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.projectmodel'),
        ),
    ]
