# Generated by Django 5.1.1 on 2024-10-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='specific_requirements',
        ),
    ]
